# Generated by Django 2.1.2 on 2020-05-22 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_num', models.CharField(max_length=32)),
                ('goods_name', models.CharField(max_length=32)),
                ('goods_oprice', models.CharField(max_length=32)),
                ('goods_xprice', models.CharField(max_length=32)),
                ('goods_kucun', models.CharField(max_length=32)),
                ('goods_desc', models.CharField(max_length=32)),
                ('goods_detail', models.CharField(max_length=128)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Type')),
            ],
        ),
    ]
